version: '2'
services:
  node:
    tty: true
    image: docker.io/bitnami/node:20
    ports:
      - 3000:3000
    volumes:
      - .:/app
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=examendwes
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
    links: 
      - mysql:mysql
volumes:
  mysql_data: